In [1]:
import numpy as np

In [25]:
# crear dos array con random_sample y que tengan los mismos valores
array = np.random.random_sample((3,2))
print(array)

array_copy = array.copy()
print(array_copy)

[[0.17386191 0.14554853]
 [0.08084812 0.91795056]
 [0.17427391 0.04519379]]
[[0.17386191 0.14554853]
 [0.08084812 0.91795056]
 [0.17427391 0.04519379]]


In [26]:
# crear array de 3 dimensiones, 2x3x5, sin decimales y entre 0-10; extrae sus valores únicos guardándolo en una variable
array_uniform = np.random.uniform(0,10, (2,3,5)).round(1)
print(array_uniform)

valores_unicos = np.unique(array_uniform)
print(valores_unicos)

[[[7.3 2.4 9.8 3.7 8. ]
  [3.2 4.9 4.3 6.5 7.7]
  [8.5 6.6 8.  3.  3.9]]

 [[6.2 7.6 2.2 3.9 6.7]
  [5.  1.3 6.6 7.  9.4]
  [4.9 3.  3.9 6.2 7.6]]]
[1.3 2.2 2.4 3.  3.2 3.7 3.9 4.3 4.9 5.  6.2 6.5 6.6 6.7 7.  7.3 7.6 7.7
 8.  8.5 9.4 9.8]


In [27]:
# crear array de 3 dimensiones, 2x3x5, con probabilidad 0.3 y nº pruebas = 10; guarda los valores únicos en una variable
array_binomial = np.random.binomial(10, 0.3, (2,3,5))
print(array_binomial)

valores_unicos_2 = np.unique(array_binomial)
print(valores_unicos)

[[[3 3 3 3 2]
  [5 5 5 4 1]
  [4 2 3 0 3]]

 [[4 5 3 0 3]
  [4 0 2 5 3]
  [3 3 3 2 2]]]
[1.3 2.2 2.4 3.  3.2 3.7 3.9 4.3 4.9 5.  6.2 6.5 6.6 6.7 7.  7.3 7.6 7.7
 8.  8.5 9.4 9.8]


In [22]:
# elementos comunes entre valores únicos de array3 y array4
elementos_comunes = np.intersect1d(valores_unicos, valores_unicos_2)
print(elementos_comunes)

[6.]


In [23]:
# unión de elementos únicos de array3 y array4
union = np.union1d(valores_unicos, valores_unicos_2)
print(union)

[ 0.4  0.8  1.   1.1  1.3  1.6  1.9  2.   2.8  3.   3.1  3.4  3.6  3.8
  4.   4.2  4.4  4.6  5.   5.2  5.6  5.8  6.   6.1  6.5  7.   7.1  7.4
  7.5  8.   8.9  9.   9.2  9.4 10. ]


In [24]:
# ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos
diferencia = np.setdiff1d(valores_unicos, valores_unicos_2)
print(diferencia)

[ 0.4  0.8  1.1  1.3  1.6  1.9  2.8  3.1  3.4  3.6  3.8  4.2  4.4  4.6
  5.2  5.6  5.8  6.1  6.5  7.1  7.4  7.5  8.   8.9  9.   9.2  9.4 10. ]


In [29]:
# crear dos arrays usando random.rand con 80 elementos, nº entre 1-100
array1 = np.random.rand(1,100, (80))
print(array1)

array2 = np.random.rand(1,100, (80))
print(array2)

[[[0.20616578 0.0706148  0.1202535  ... 0.0426785  0.4772042  0.25728111]
  [0.03518197 0.78802137 0.06469115 ... 0.47429273 0.71608268 0.51019929]
  [0.53825139 0.64187779 0.70477597 ... 0.87412491 0.56389396 0.73140258]
  ...
  [0.29056813 0.27286195 0.04147346 ... 0.92626183 0.51430568 0.98845193]
  [0.21853032 0.19535344 0.50044674 ... 0.47054914 0.9945856  0.14174924]
  [0.76577793 0.71881374 0.55219617 ... 0.26470032 0.69926938 0.7428835 ]]]
[[[0.9231398  0.80632971 0.90817497 ... 0.40340909 0.35709415 0.66091447]
  [0.31198068 0.02484426 0.9943084  ... 0.44313906 0.04424215 0.57897722]
  [0.62016334 0.62936604 0.42208687 ... 0.98395044 0.5794666  0.28181444]
  ...
  [0.09871338 0.84212381 0.69648883 ... 0.75794201 0.19513054 0.96672644]
  [0.44969021 0.51577839 0.53693265 ... 0.07630316 0.89405744 0.95128704]
  [0.8416947  0.18280043 0.60650744 ... 0.07113453 0.35085461 0.16397443]]]


In [31]:
# Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2
array1 = np.unique(array1)
print(array1)

array2 = np.unique(array2)
print(array2)

[4.20569473e-04 4.23931935e-04 4.52828258e-04 ... 9.99644779e-01
 9.99743029e-01 9.99770665e-01]
[7.44098124e-05 1.35068799e-04 2.64991850e-04 ... 9.99900469e-01
 9.99967303e-01 9.99995957e-01]


In [32]:
# Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3
array3 = np.setdiff1d(array1, array2)
print(array3)

[4.20569473e-04 4.23931935e-04 4.52828258e-04 ... 9.99644779e-01
 9.99743029e-01 9.99770665e-01]


In [33]:
# Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4
array4 = np.setdiff1d(array2, array1)
print(array4)

[7.44098124e-05 1.35068799e-04 2.64991850e-04 ... 9.99900469e-01
 9.99967303e-01 9.99995957e-01]


In [34]:
# Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5
array5 = np.intersect1d(array1, array2)
print(array5)

[]


In [1]:
# ¿Cuál es la relación que existe entre todos estos arrays?
forma_1 = np.shape(array1)
print(forma_1)

forma_2 = np.shape(array2)
print(forma_2)

forma_3 = np.shape(array3)
print(forma_3)

forma_4 = np.shape(array4)
print(forma_4)

forma_5 = np.shape(array5)
print(forma_5)

# Todos los arrays tienen la misma longitud salvo array5 porque es una intersección entre array1 y array2 y no tienen elementos en común

NameError: name 'np' is not defined