In [32]:
import numpy as np

# crear array bidimensional 5x3
array1 = np.random.rand(5,3)
print(array1)

# valor de la primera fila y segunda columna
print('Esto es la primera fila y segunda columna: \n', array1[0,1])

# segunda fila y dos primeras columnas
print('Esto es la segunda fila y las dos primeras columnas: \n', array1[1,0:2])

# extraer filas pares y todas las columnas 
print('Esto son las filas pares (incluyendo 0) y todas las columnas: \n', array1[0:6:2,:])

# valores > 0.5
print('Estos son los valores mayores que 0.5: \n', array1[array1 > 0.5])

# valores < 0.2 y > 0.5
print('Estos son los valores menores 0.2 y mayores que 0.5: \n', array1[(array1 < 0.2) | (array1 > 0.5)])

[[0.52482371 0.99736244 0.05141989]
 [0.97376251 0.90325829 0.30874732]
 [0.90166818 0.50300148 0.8303458 ]
 [0.97632198 0.97230496 0.26296933]
 [0.08165811 0.59702644 0.30730015]]
Esto es la primera fila y segunda columna: 
 0.9973624441268643
Esto es la segunda fila y las dos primeras columnas: 
 [0.97376251 0.90325829]
Esto son las filas pares (incluyendo 0) y todas las columnas: 
 [[0.52482371 0.99736244 0.05141989]
 [0.90166818 0.50300148 0.8303458 ]
 [0.08165811 0.59702644 0.30730015]]
Estos son los valores mayores que 0.5: 
 [0.52482371 0.99736244 0.97376251 0.90325829 0.90166818 0.50300148
 0.8303458  0.97632198 0.97230496 0.59702644]
Estos son los valores menores 0.2 y mayores que 0.5: 
 [0.52482371 0.99736244 0.05141989 0.97376251 0.90325829 0.90166818
 0.50300148 0.8303458  0.97632198 0.97230496 0.08165811 0.59702644]


In [34]:
# crear dos array de 3 dimensiones
array2 = np.random.rand(2,3,5)
array3 = np.random.rand(3,2,5)

# análisis exploratorio de los arrays creados
def analisis():
    lista_array = [array2, array3]
    for propiedad in lista_array:
        print(propiedad.shape)
        print(propiedad.size)
        print(propiedad.ndim)
        print(propiedad.dtype)

analisis()

# suma dos arrays
# suma = array2 + array3 no se puede porque no tienen la misma forma

# .reshape() y .transpose()
array3_transpose = array3.transpose(1,0,2)
array3_reshape = array3.reshape(2,3,5)

suma = array2 + array3_transpose
print(suma)

resta = array2 - array3_reshape
print(resta)

multiplicacion = array2 * array3_transpose
print(multiplicacion)

division = array2 / array3_reshape
print(division)


(2, 3, 5)
30
3
float64
(3, 2, 5)
30
3
float64
[[[1.23507537 1.01839862 0.45960222 0.30939579 0.39553112]
  [1.22092173 1.18429155 1.74239767 1.12817454 1.27394018]
  [1.0706914  0.97090933 0.96231356 0.93389756 0.41085454]]

 [[1.0920196  0.935974   0.46452287 1.2243196  0.75080431]
  [1.41055104 0.47218603 1.47690214 0.7539586  1.47077291]
  [0.79669956 1.11018517 1.21018863 1.24081537 1.02328705]]]
[[[-0.12064602 -0.19823631 -0.25620242 -0.30006673 -0.32326739]
  [ 0.04158759  0.85057808  0.32130414  0.07138118  0.65037375]
  [-0.49424543  0.20186645 -0.93356904  0.15783281 -0.13925339]]

 [[-0.03248197  0.8857116  -0.90582048 -0.11927023 -0.27558433]
  [-0.09955322 -0.01340578 -0.36823029 -0.30890262  0.51784278]
  [-0.10718269  0.38180131 -0.26243929 -0.45649001 -0.46160767]]]
[[[0.37771393 0.24945953 0.03639863 0.00142143 0.01298576]
  [0.31402844 0.27480419 0.74412622 0.20605749 0.31633024]
  [0.2552711  0.23456527 0.05374797 0.21165759 0.04215534]]

 [[0.25004247 0.01557256 0.01